apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdwebui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdwebui
  template:
    metadata:
      labels:
        app: sdwebui
    spec:
      volumes:
      - name: stable-diffusion-models
        hostPath:
          path: /comfyui-models # Need to sync all models in node's user-data
      - name: comfyui-outputs
        persistentVolumeClaim:
          claimName: comfyui-outputs-pvc # Need to apply sd-outputs-s3.yaml first
      containers:
      - name: sdwebui
        image: 879660699388.dkr.ecr.ap-southeast-1.amazonaws.com/sdwebui-images:latest
        ports:
        - containerPort: 7860
        volumeMounts:
        - mountPath: /app/SDWebUI/models
          name: stable-diffusion-models
        - mountPath: /app/SDWebUI/output
          name: comfyui-outputs
        resources:
          requests:
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1
        readinessProbe:
          httpGet:
            path: /
            port: 7860            
          initialDelaySeconds: 90
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 7860            
          initialDelaySeconds: 120
          periodSeconds: 10
